[PR 1] DEV-177 BLCU fixes
HyperloopUPV-H8/h8-backend pull request #111
Opened 2023-05-23 18:12 UTC by jmaralo

After integrating the BLCU logic with FW, here are the fixes necessary to make it work, it also features an update to notify the progress to the frontend. However, This is currently not supported by the frontend and will cause issues.

2023-05-23 18:16 UTC, smorsua commented on src/blcu/download.go
> +	download := NewDownload(786432) // Size of the flash memory (downlaod size)
Put size in const FlashMemorySize

2023-05-23 18:25 UTC, smorsua commented on src/blcu/download.go
> +	download, err := blcu.ReadTFTP()
I would do the following: ReadTFTP blocks until it downloads or errors and it accepts a callback (onProgress), where you receive the progress and can whatever you want to do with it.

2023-05-23 18:44 UTC, smorsua requested changes
Pretty clear implementation, I'd avoid concurrency in some places to avoid using many channels and such

2023-05-23 18:44 UTC, smorsua commented on src/blcu/download.go
> +	IsSuccess  *bool   `json:"success,omitempty"`
Make IsSuccess value and send false while percentage is less than 100

2023-05-23 18:44 UTC, smorsua commented on src/blcu/download.go
> +type Download struct {
Download would store the onProgress callback passed to ReadTFTP

2023-05-23 18:44 UTC, smorsua commented on src/blcu/download.go
> +		download.notify <- n
You'd call onProgress here, with the percentage

2023-05-23 18:44 UTC, smorsua commented on src/blcu/download.go
> +func (download *Download) abort(err error) {
Why do you need to send the error through a channel? receiver.WriteTo returns an error, so consumers should check that error to determine if the download failed

2023-05-23 18:44 UTC, smorsua commented on src/blcu/download.go
> +	download.resultChan <- DownloadResult{
If receiver.WriteTo block, you dont need this channel

2023-05-25 10:05 UTC, smorsua approved these changes
LGTM

2023-05-25 16:09 UTC, lipezaballa approved these changes

2023-05-25 16:24 UTC, merged