[PR 1] Fixed ws_handler deadlock, pipe_readers and simple subscription
HyperloopUPV-H8/h8-backend pull request #115
Opened 2023-06-02 14:34 UTC by smorsua

The pipe_readers are structs that read from the pipes in a particular way. Each pipe has a map that goes from id (first two bytes of any message) to reader. Right now, we have two types of readers:
- For JSON messages from the boards, we read until we find a 0x00.
- For StateOrder messages, part of the message is the number of orders it carries, and so we can calculate the size of the message i.e the amount of bytes we have to read.

A deadlock has been fixed in the ws_handler. The code to subscribe to a module is now common to all modules with a subscription.

Finally, the subcriptions from the frontend now provide an id for each subcription to avoid errors relating to the same connection unsubscribing and subscribing to the same module in shorts periods of time (if the order was not correct, the subscription could have failed).

2023-06-06 02:44 UTC, jmaralo requested changes
Just two minor things

2023-06-07 14:18 UTC, smorsua reviewed
lgtm

2023-06-07 14:18 UTC, smorsua commented on src/main.go
> +			case "addStateOrders":
Put values in const

2023-06-08 14:25 UTC, lipezaballa approved these changes

2023-06-10 11:47 UTC, merged