[PR1] DEV-152 Vehicle Refactor
HyperloopUPV-H8/h8-backend pull request #98
Opened 2023-04-24 18:02 UTC by smorsua

The Measurement model has been split into NumericMeasurement, EnumMeasurement and BooleanMeasurement, so all of the following changes are to accommodate these new models. We store them as any differentiate them by using a type switch.

2023-04-24 19:29 UTC, lipezaballa requested changes

2023-04-24 20:54 UTC, jmaralo requested changes
It's ok, but I prefer the previous implementation of the parser where each ID had a kind associated and then a map from kind to decoder and from kind to encoder, it was more flexible and easier to use. Then to use it with the rest you just had to convert the internal parser types to PacketUpdate, Order, etc.

I feel most changes to vehicle just make it harder to read and make functions longer.

If you don't want to roll back some changes is alright because this will work and not much more changes need to be made, but that is my general impression

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/constructor.go
> +func createSniffer(global excel_models.GlobalInfo, config Config, trace zerolog.Logger) sniffer.Sniffer {
put this and `getFilter` in the sniffer module

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/constructor.go
> +func createPipes(global excel_models.GlobalInfo, dataChan chan<- packet.Packet, onConnectionChange func(string, bool), config Config, trace zerolog.Logger) map[string]*pipe.Pipe {
put this and `getOnConnectionChange` in the pipe module

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/constructor.go
> +func createPacketParser(global excel_models.GlobalInfo, boards map[string]excel_models.Board, trace zerolog.Logger) (packet_parser.PacketParser, error) {
put this and all the necessary functions in the packet parser module

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/constructor.go
> +}
split into three functions: `getIPIPfilter`, `getUDPFilter` and `getTCPFilter`

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/vehicle.go
> +func (vehicle *Vehicle) Listen(updateChan chan<- models.PacketUpdate, protectionChan chan<- models.Protection) {
split into two functions

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/vehicle.go
> +		switch id := raw.Metadata.ID; {
This is not decoding orders but it could receive orders

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/vehicle.go
> +			fmt.Println("UNEXPECTED VALUE")
use trace instead

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/vehicle.go
>  func (vehicle *Vehicle) SendOrder(order models.Order) error {
missing bitarray encoding (even if FW isn't using it put the code and we can comment it if we don't want it)

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/vehicle.go
> +		switch typedValue := value.(type) {
put the switch in its own function

2023-04-24 20:54 UTC, jmaralo commented on src/vehicle/vehicle.go
> +			trace.Error().Msg("order field value not recognized")
store the type (with `.Str("type", fmt.Sprintf("%T", field.Value))`) and the name (with `.Str("name", name)`)

2023-04-25 08:28 UTC, lipezaballa approved these changes

2023-04-25 09:30 UTC, merged